### ISSUE TITLE
Bahasan Big Data

### ISSUE THREAD

**Issue by threeal** [threeal-archive/research#11]
### Task

- [x] cari tahu perbedaan analytics dan analysis di [sini](https://medium.com/datadriveninvestor/what-is-the-difference-between-analysis-and-analytics-8b03bac7aa80)
- [x] pelajari soal 4-V of big data di [sini](https://www.gutcheckit.com/blog/webinar-re-cap-solutions-for-zero-based-budgeting/)
- [x] pelajari soal veracity di [sini](https://www.gutcheckit.com/blog/veracity-big-data-v/)
- [x] cek website [weblizard](https://www.weblyzard.com/) (perusahaan data capture and analyze)
- [x] pelajari soal business intelligence di [sini](https://medium.com/@jrendz/pengenalan-business-intelligence-c36232510531) (bahasa indonesia)
- [x] buat bahasan dari 5 example web intelligence jenis BI di [sini](https://public.tableau.com/en-us/gallery/?tab=viz-of-the-day&type=viz-of-the-day) **(DEADLINE 12 OKTOBER)**

**Comment by threeal** [comment]
# 1 - Pengenalan Big Data dan Analytics

<details><summary>detail bahasan</summary><p>

![image](https://user-images.githubusercontent.com/10202888/94524837-5e2aa800-025d-11eb-9ad0-ddc1d60d2f36.png)

- Big data aliran data yang banyak secara terus menerus
- dilakukan analisa dari data yang ada
- sehingga ditemukan hasil yang bisa mempengaruhi keputusan

![image](https://user-images.githubusercontent.com/10202888/94525739-b9a96580-025e-11eb-8017-aec8e2f1fc81.png)

- sebelum big data sudah ada yang namanya bussiness intelligent (kecerdasan bisnis)
- problemnya kecerdasan bisnis membutuhkan data yang terstruktur dan sangat detail, lain halnya dengan adanya big data.
- pada big data, data yang besar tidak akan menjadi masalah karena bisa dilakukan mapping
- kelebihan big data pada pemrosesan data yang abstract, termasuk image dan video

![image](https://user-images.githubusercontent.com/10202888/94526222-6a176980-025f-11eb-93d9-70a0ec30dd50.png)

- contoh web analytics [disini](https://unep.ecoresearch.net/weblyzard/en/).
- analytics berbeda dengan analysis? (cari tahu lagi, baca [disini](https://medium.com/datadriveninvestor/what-is-the-difference-between-analysis-and-analytics-8b03bac7aa80))
- analytics mudah dikembangkan untuk masuk ke analisa lainnya

![image](https://user-images.githubusercontent.com/10202888/94526790-40ab0d80-0260-11eb-88c9-3939d388f7dc.png)

- kita sebagai orang komputer kadang kurang tahu bagaimana data harus diolah

![image](https://user-images.githubusercontent.com/10202888/94526880-620bf980-0260-11eb-832b-510d6615742a.png)

- ketika sudah masuk ke use case maka sifat dari analytics akan lebih mudah buat dipahami

![image](https://user-images.githubusercontent.com/10202888/94526934-7a7c1400-0260-11eb-9a1e-349f53bac88d.png)

- satelit yang dibuat khusus untuk mengamati perubahan iklim, terutama masalah global warming
- sebagai contoh kasus satelit NOAA, mereka sudah mulai ke analytics tidak hanya analysis

![image](https://user-images.githubusercontent.com/10202888/94527048-a0a1b400-0260-11eb-8545-c566f73d6fe5.png)

- diperlukan berbagai macam disiplin ilmu untuk menganalisa, seperti computer vision, dsb.

![image](https://user-images.githubusercontent.com/10202888/94527137-bdd68280-0260-11eb-8c60-d72137859865.png)

![image](https://user-images.githubusercontent.com/10202888/94527162-c7f88100-0260-11eb-9dd8-8d2b636fde44.png)

![image](https://user-images.githubusercontent.com/10202888/94527241-e3638c00-0260-11eb-8bc5-48c3b40343f2.png)

- masalah veracity, data bolong bolong atau data yang tidak valid.

![image](https://user-images.githubusercontent.com/10202888/94527576-6258c480-0261-11eb-8232-695fe75de375.png)

- social influencer??
- pandanganku sih hubungan lokasi pengguna twitter, dan bagaimana sebuah twit direply, atau diakses oleh orang lain (dilihat dilike, dsb.)
- apapun analisanya setiap orang bisa menerjemahkan sendiri ini sebenernya apa.

![image](https://user-images.githubusercontent.com/10202888/94527972-f88cea80-0261-11eb-871e-17481daee4c6.png)

- another example, word tree, hubungan sebuah kata dengan kata lain dalam berbagai bahasa juga
- perusahaan 247 mengerjakan hal seperti itu??

![image](https://user-images.githubusercontent.com/10202888/94528104-1f4b2100-0262-11eb-9117-a465a2f663f2.png)

![image](https://user-images.githubusercontent.com/10202888/94528168-338f1e00-0262-11eb-9065-a7afcea226aa.png)

- orang yang melakukan query big data mulai ada banyak, dari amerika, eropa
- presentasi ini disponsori oleh [weblizard](https://www.weblyzard.com/)
- pak dosen kekurangan anak s1 buat ngerjain web intelligence sama big data
- ini merupakan teknologi yang bakal disruptif di masa depan, bakal kepake banyak di artificial intelligence
- contoh di jakarta, software ai di pasang di perempatan digunakan untuk memaksa kendaraan lebih berhati hati di simpangan, untuk mengurangi tingkat kecelakaan

"enggak sulit, fasilitas sudah ada, cuma kita agak lemah di analisa data" - pak dosen.

</p></details>

**Comment by mpuhambyah** [comment]
Nice slur

**Comment by threeal** [comment]
# 2- Contoh Web Intelligence jenis Business Intelligence

ditulis juga di [google docs](https://docs.google.com/document/d/1NgP4zQT2ZUnTbH62kAGfbiDxlpMq1M8vB1PoqPkBrFw/edit?usp=sharing)

<details><summary>detail bahasan</summary><p>

## Top 20 Football Clubs by Revenue ([link](https://public.tableau.com/en-us/gallery/revenue-football-clubs?tab=viz-of-the-day&type=viz-of-the-day))

![image](https://user-images.githubusercontent.com/10202888/95680838-8a9fd600-0c06-11eb-8dd0-be4513903ef0.png)

Pada visualisasi ini dijelaskan pendapatan dari 20 klub bola terbesar selama musim 2018/19. Nilai yang diperlihatkan pada visualisasi ini hanyalah besar pendapatan dari masing masing klub bola dengan Barcelona mendapatkan pendapatan terbesar sebesar 841 juta euro, disusul oleh Real Madrid sebesar 757 juta euro dan Manchester United sebesar 712 juta euro. Sebagai tambahan juga dijelaskan dengan garis berwarna biru bahwa 5 tim dari Inggris masuk ke 10 besar pendapatan tertinggi dan 8 tim dari Inggris masuk ke 20 besar pendapatan tertinggi. Dari sini bisa ditarik kesimpulan bahwa klub asal inggris memiliki pendapatan yang tergolong tinggi sehingga kemungkinan orang orang menyukai pertandingan yang dimainkan oleh klub asal inggris tersebut.

## How is the Stock Market Performing? ([link](https://public.tableau.com/en-us/gallery/how-stock-market-performing?tab=viz-of-the-day&type=viz-of-the-day))

![image](https://user-images.githubusercontent.com/10202888/95680969-78726780-0c07-11eb-98ad-522dd2d597ab.png)

Pada visualisasi ini dijelaskan nilai dan kondisi stock market dari berbagai macam kategori. Luas kotak pada visualisasi menggambarkan banyaknya nilai dari stock tersebut sedangkan warna merah hingga hijau menunjukkan kondisi dari stock market apakah naik atau turun. Data yang ada di visualisasi diambil per 24 Februari 2020. Disini setiap stock market dibagi menjadi berbagai macam kategori mulai dari information technology, health care, financials, dan lain sebagainya. Dari visualisasi yang diperlihatkan kebanyakan stock market mengalami penurunan dengan indikasi persegi yang berwarna kemerahan.. Hal ini kemungkinan terjadi juga diiringi dengan merebaknya wabah Covid-19 pada awal tahun 2020 yang menimbulkan penurunan ekonomi di Cina dan negara negara lain yang juga terdampak.

## Airbnb Listing in Berlin ([link](https://public.tableau.com/en-us/gallery/airbnb-listings-berlin?tab=viz-of-the-day&type=viz-of-the-day))

![image](https://user-images.githubusercontent.com/10202888/95681511-6fcf6080-0c0a-11eb-91d1-ac7753e13529.png)

Pada visualisasi ini dijelaskan listing Airbnb di kota berlin hingga bulan mei 2019 dengan menunjukkan lokasi tiap listing di peta, trend dari listing tersebut, serta summary dari data yang ada. Setiap listing dibagi menjadi dua jenis yakni untuk persewaaan keseluruhan rumah / apartemen dengan indikasi berwarna merah dan persewaan private (sebagian ruang) dengan indikasi berwarna abu-abu. Dari lokasi bisa dilihat bahwa umumnya listing terletak di pusat kota dengan melihat begitu padatnya titik merah dan abu abu di pusat sedangkan sebagian kecil yang lain berada di luar. Dari trend bisa dilihat juga semakin lama trend cenderung naik namun dengan pola yang sama di sepanjang tahun dimana pada sekitaran desember-januari listing selalu lebih rendah dari bulan bulan yang lain. Dari sini dapat disimpulkan bahwa umumnya selain jumlah ketersediaan airbnb di kota besar cenderung besar, hal ini juga diimbangi karena besarnya permintaan karena pada peta, besar lingkaran dipengaruhi oleh banyaknya review dari listing tersebut. Selain itu dari tahun ke tahun jumlah listing semakin banyak yang berarti persaingan antar listing juga semakin ketat walaupun di sekitaran desember-januari listing akan cenderung turun.

## StarCraft II Player Network ([link](https://public.tableau.com/en-us/gallery/starcraft-ii-player-network?tab=viz-of-the-day&type=viz-of-the-day))

![image](https://user-images.githubusercontent.com/10202888/95682012-3fd58c80-0c0d-11eb-88b6-21ea039fba51.png)

Pada visualisasi ini dijelaskan persebaran pemain StarCraft II dengan melihat seberapa aktif pemain tersebut dan seberapa banyak pertandingan yang ia lakukan. Setiap titik menggambarkan pemain yang setidaknya telah bermain pada lebih dari 60 pertandingan, dengan besar titik menggambarkan seberapa banyak pertandingan yang ia lakukan. Setiap titik dibedakan berdasarkan warna yang menggambarkan region asal pemain tersebut yang berupa merah untuk eropa, kuning untuk korea, dan lain sebagainya. Kemudian ada garis penghubung tiap titik yang menunjukkan pertandingan antara pemain yang dihubungkan dengan garis dengan setidaknya 4 pertandingan. Dari visualisasi tersebut dapat disimpulkan bahwa Pemain StarCraft II kebanyakan berasal dari region eropa dan korea, yang mana region eropa cenderung bermain dengan sesama sedangkan region korea lebih luas cakupannya untuk bertanding dengan region lain. Pada visualisasi juga terlihat pemain amerika yang sebagian kecil menyebar hingga di sisi region korea yang menunjukkan pertandingan yang sering dilakukan oleh kedua region tersebut.

## How America Uses Its land ([link](https://public.tableau.com/en-us/gallery/how-america-using-its-land?tab=viz-of-the-day&type=viz-of-the-day))

![image](https://user-images.githubusercontent.com/10202888/95684133-9e086c80-0c19-11eb-80f7-efdf746b3a1b.png)

Pada visualisasi ini dijelaskan penggunaan lahan di amerika untuk berbagai jenis industri mulai dari peternakan dengan warna kuning, hutan dengan warna hijau, ladang dengan warna cokelat, dan lain sebagainya. Dari visualisasi ini akan tampak bahwa secara dominan, tanah di amerika digunakan untuk peternakan yang mendominasi sebagian besar wilayah barat amerika yang kemudian disusul oleh ladang dan hutan di sebelah timurnya. Selain itu juga diperlihatkan bahwa penggunaan tanah untuk area perkotaan paling banyak ada di wilayah timur amerika. Hal ini bisa disimpulkan bahwa di bagian timur amerika, lahan umumnya hanya digunakan untuk wilayah perkotaan secara penuh dan menyisakan wilayah lain tanpa kegunaan industri selain kehutanan.. banyaknya hutan di sebelah barat juga dipengaruhi oleh wilayah geografis amerika di sebelah barat yang cenderung berhutan. kemudian agak ke barat sedikit akan ditemui tanah yang digunakan untuk ladang, hal ini sesuai juga dengan geografis wilayah tersebut yang cenderung subur karena dialiri oleh sungai mississippi. sedangkan terakhir lebih ke barat lagi wilayahnya mulai memiliki sedikit urban area namun didominasi oleh tanah untuk peternakan, hal ini juga terjadi karena faktor geografis yang mana wilayah tersebut cenderung tidak sesubur wilayah lain di amerika. Dari sana bisa dipahami bahwa untuk tujuan peternakan wilayah barat merupakan yang cocok untuk digunakan, untuk tujuan ladang wilayah tengah di sekitaran sungai mississippi yang cocok untuk digunakan dan terakhir untuk wilayah perkotaan maupun hutan lebih cocok untuk menggunakan wilayah timur. walaupun tidak dimungkiri juga bahwa wilayah barat juga cocok untuk investasi wilayah perkotaan yang suatu saat juga pasti akan bernilai tinggi.

</p></details>

**Comment by threeal** [comment]
# 12 - Lanjutan Big Data

<details><summary>detail bahasan</summary><p>

## Big Data IBM Version

![image](https://user-images.githubusercontent.com/10202888/102182521-048e5d00-3edf-11eb-819c-f2f62ce2dc87.png)

- big data berbasis kepada AI dan computer intelligence.
- inti dari big data ada 4, volume, variety, velocity, dan veracity.
- big data karena data yang diproses sangat besar dan umumnya selalu berubah.
- variety, data dihasilkan melalui beragam cara dan oleh beragam perangkat.
- IBM menambah bagian keempat yaitu veracity karena data yang ada umumnya tidak tentu.

## Skala Big Data

![image](https://user-images.githubusercontent.com/10202888/102182842-84b4c280-3edf-11eb-9684-fda27b4930e4.png)

- dahulunya data hanya berbentuk teks dan ukurannya hanya beberapa MB, dan diakses secara periodik (beberapa semester, minggu, dsb.).
- berbeda ketika data yang ada berbentuk lain seperti video, sehingga juga menghasilkan ukuran yang lebih besar hingga petabyte serta proses dilakukan secara real-time hampir setiap saat selalu ada.

## Analytics Capabilites are Evolving

![image](https://user-images.githubusercontent.com/10202888/102183133-effe9480-3edf-11eb-89fc-91c86d4fb151.png)

- dahulu data bersikap descriptive analytics, sesuatu yang bisa dilihat, dianalisa dari apa yang sudah terjadi, sehingga sifatnya "what if?".
- dari descriptive analytics lanjut ke diagnostics analystics, mencari alasan dari suatu kejadian.
- kemudian lanjut ke predictive analytics, apa yang kemudian akan terjadi dari alasan yang sudah ada.
- predictive analytics sudah mulai membutuhkan AI.
- dan terakhir adalah prescriptive analytics yang memungkinkan kita melakukan tindakan yang memungkinkan apa yang akan terjadi.
- ini bukanlah daftar tingkatan tetapi daftar urutan sehingga untuk melakukan prescriptive analytics masih diperlukan predictive analytics dan sebelum-sebelumnya.
- bukan trial and error, tapi lebih ke scientific, sehingga masih berpaku pada data.
- analytics dan analysis berbeda, seperti contoh tableau kemarin adalah analysis karena yang dijelaska sangat mendetail.
- inertia, analisis yang dilakukan tidak merubah keadaan, imperative, analisa yang dilakukan memiliki arti yang sangat penting sehingga dapat memberi kekuasaan kepada yang mampu melakukan analisa.

## Overview of the Analytics Process Model

![image](https://user-images.githubusercontent.com/10202888/102185029-01956b80-3ee3-11eb-83e0-080a64a3574b.png)

- "apakah analytics memerlukan analysis?" jawabannya bisa ya maupun tidak. karena sebagai contoh mungkin ada supervised maupun unsupervised. unsupervised sendiri tidak memerlukan analysis karena dia tidak terarah, namun juga hasilnya akan tidak terprediksi. sedangkan supervised memerlukan analysis karena terarah, berdasarkan analisa sebelumnya yang sudah dilakukan.
- salah satu perusahaan yang melakukan unsupervised learning adalah google dalam membuat recommendation engine.
- perusahaan besar mulai banyak yang menentukan versi big datanya masing-masing, seperti IBM maupun Amazon.
- yang pasti big data pasti memerlukan AI.

</p></details>

**Comment by threeal** [comment]
# 13 - Riset Web Intelligence dan Big Data

- [ ] Google's Neural Machine Translation System: Bridging the Gap between Human and Machine Translation, [arXiv](https://arxiv.org/abs/1609.08144), [PDF](https://drive.google.com/file/d/1pJZuWn7yl1RL-KaKNifPiag8S_dhVIeh/view?usp=sharing).

**Comment by threeal** [comment]
EAS Sudah berakhir, have a nice day
