### ISSUE TITLE
Bahasan WSN dan IoT

### ISSUE THREAD

**Issue by threeal** [threeal-archive/research#12]
### Task

- [x] cek [wiki](https://en.wikipedia.org/wiki/Internet_of_things) soat iot (internet of thing)
- [x] cek [wiki](https://en.wikipedia.org/wiki/Wireless_sensor_network) soal wsn (wireless sensor network)
- [x] cek cara kerja intel computed stick [disini](https://screen.cloud/learn/guide-intel-compute-stick)
- [x] tambahi penjelasan alat: termasuk sensor apa? aktif/pasif? digital/analog? link dari datasheet?
- [x] jelaskan dengan tulisan (1 halaman A5 tulis tangan) cara kerja modul IoT [ini](https://drive.google.com/file/d/1hAWWa4k3_ulQQcrN-v21au3p5_mqK_fz/view?usp=sharing).
- [x] presentasi lagi project kelompok kemarin dengan menggunakan protokol MQTT.
- [x] install MQTT broker, publisher, dan subsriber di komputer beserta mencoba mengirim data.

**Comment by threeal** [comment]
# 0 - Cakupan Materi

- konsep dasar iot (dan contoh aplikasinya)
- komponen penyusun iot
- cloud storage sebagai penyimpanan iot
- konsep wireless sensor network (wsn)
- protokol routing dan lokalisasi wsn
- konsep under water sensor network (uwsn)
  - dibawah air sinyal yang umum digunakan tidak bisa bekerja, solusinya menggunakan sinyal akustik
  - dibawah air tidak bisa menggunakan gps, solusinya menggunakan sistem lokalisasi (set manual??)
- protokol routing dan lokalisasi uwsn
- protokol komunikasi antar sensor
- protokol komunikasi sensor network ke cloud storage
- aplikasi wsn menggunakan microcontroller dan sbc
- penerapan iot di bidang lain (pertanian, transportasi, kesehatan, dsb.)

**Comment by threeal** [comment]
# 1 - Pengenalan Jaringan Sensor

<details><summary>detail bahasan</summary><p>

![image](https://user-images.githubusercontent.com/10202888/94633531-c332dc00-02f7-11eb-8c4a-3d0a812e9509.png)

### keunggulan jaringan sensor dan independen sensor

- jarak jangkauan yang luas
- mengurangi redudancy
- akurasi yang lebih bagus
- node sensor juga bisa sebagai forwader atau router

### sensor

- sensing, mengumpulkan informasi fisika dalam suatu lingkungan
- sensor, perangkat yang melakukan sensing dan mengubah nilai yang ada ke energi listrik

![image](https://user-images.githubusercontent.com/10202888/94634113-5b7d9080-02f9-11eb-872d-406a707afe86.png)

### tantangan pada wsn

- sensor mempunyai power supply baterai
- kemudahan mengganti baterai
- kemudahan recharge baterai
- baterai yang sulit diganti dan dicharge harus punya durasi lama
- energi pada setiap layer punya konsumsi yang sedikit

![image](https://user-images.githubusercontent.com/10202888/94634316-e78fb800-02f9-11eb-8199-06065d4ad83f.png)

![image](https://user-images.githubusercontent.com/10202888/94634415-2faeda80-02fa-11eb-8b69-24ffe711e726.png)

![image](https://user-images.githubusercontent.com/10202888/94634667-da26fd80-02fa-11eb-9a25-08e6e6f3437b.png)

![image](https://user-images.githubusercontent.com/10202888/94634946-a7c9d000-02fb-11eb-988f-338f038b0857.png)

![image](https://user-images.githubusercontent.com/10202888/94635475-eca23680-02fc-11eb-9b44-53fd1bf6aaf8.png)

- ta yang menggunakan raspberry dan [intel compute stick](https://www.intel.com/content/www/us/en/products/boards-kits/compute-stick.html), agar neural network jalan di sbc
- tidak cocok menggunakan wsn karena selain bandwith terbatas adalah boros energi (energi yang digunakan untuk mengirim data lebih boros walaupun dibandingkan untuk komputasi neural network)
- ada data yang disimpan secara lokal dan ada data yang disimpen ke server secara (hampir) real time

> kebanyakan perusahaan enggak lihat transkip, secara yang jadi kepala biasanya orang yang biasa biasa aja

> jaman pak dosen dulu umumnya lulus 6 tahun, sebelumnya lagi malah 7 tahun

> tahun 98, mungkin kalian belum lahir, dollar yang sebelumnya 4500 sampai 98 20rb, karena habis lulus jadi gak tahu harus ngapangapain cuma lihat orang demo (secara rumah ortu deket unair), saya dulu enggak ikut demo, karena hanya orang biasa aja tapi dulu takut ketangkap, walaupun yang rame di trisakti sebenernya kasus di surabaya juga sama saja, kondisinya mungkin hampir sama dengan sekarang, bedanya dulu karena politik sedangkan sekarang karena wabah

</p>

**Comment by threeal** [comment]
# 3 - LEACH Protocol

- Low Energy Adaptive Clustering Hierarchy with Deterministic Cluster-Head Selection ([journal](http://vs.inf.ethz.ch/publ/se/IEEE_MWCN2002.pdf))
- Tambahan catatan lain ([nadhanum](https://echo.notable.app/4e5a6276d3946be31c8ac552808de87a03afedb1))

<details><summary>detail bahasan</summary><p>

## Introduction

![image](https://user-images.githubusercontent.com/10202888/95934413-fc407580-0dfa-11eb-82c0-b8ca222218a7.png)

- LEACH stands for Low-Energy Adaptive Clustering Hierarchy
  - tiap node terdiri atas hierarchy yang terbagi berdasar cluster secara adaptive
  - tiap node di cluster mengirim data ke cluster head, kemudian cluster head akan mengirimkan ke sink
- This WSN is considered to be a dynamic clustering method
  - tiap node diasumsikan homogen (punya perangkat yang sama)
  - cluster head dipilih secara bergantian secara dinamis
- LEACH has two phases.
  - dalam setiap round ada dua fase yakni setup state dan steady state
- LEACH merupakan routing protocol pada WSN yang base stateion (sink)-nya fixed, dan sensor nodes nya homogen
- LEACH menghemat energy dengan aggregation dan adaptive clustering
  - aggregation melakukan compression (seperti dua node yang berdekatan dianggap satu, bukan kompresi data)
  - pengiriman data tidak dilakukan langsung ketika data diterima, tapi menunggu selang waktu tertentu, menunggu data lain juga terkumpul
- Kegunaan protocol ini adalah untuk meningkatkan masa aktif jaringan, karena jika ada salah satu node mati maka bisa mengganggu keseluruhan node

![image](https://user-images.githubusercontent.com/10202888/95934775-e54e5300-0dfb-11eb-8ffa-5b5c91aa451c.png)

- Alasan penggunaan LEACH untuk protokol WSN adalah fakta bahwa node di jaringan akan menjadi tidak berguna jika baterainya habis
- LEACH network terdiri atas berbagai nodes, salah satunya bertugas sebagai cluster head
  - tugas cluster head adalah untuk mengumpulkan data dari cluster member, dilakukan agregasi, kemudian mengirimkannya ke base station (sink)
  - LEACH bersifat dinamik karena tugas cluster head digilir (tidak selalu menggunakna node yang sama)

# Direct Versus Minimum Transmission

![image](https://user-images.githubusercontent.com/10202888/95934806-f8612300-0dfb-11eb-96a3-30fa9973b870.png)

- minimum transmission energy = multi-hop transmission
- energi yang dibutuhkan node tidak hanya tranmisi, tapi juga receive
- kesimpulannya direct transmission lebih cepat dalam pengiriman daripada multi-hop transmission, tapi multi-hop akan lebih hemat energi dibandingkan dengan direct transmission
- pada WSN, keterlambatan waktu tidak masalah selama masih di batasan yang aman, yang terpenting adalah penggunaan energi yang tidak berlebihan

![image](https://user-images.githubusercontent.com/10202888/95935539-acaf7900-0dfd-11eb-9a25-157467a33b3f.png)

- alasan penggunaan cluster head untuk mengumpulkan data terlebih dahulu sebelum dikirim ke sink dibandingkan tiap sensor langsung ke sink adalah:
  - penggunaan multihop, untuk menghemat energi
  - bisa dilakukan agregasi
  - menghindari collision antara dua node karena terlalu banyak node yang mengirim ke tujuan yang sama
  - pengiriman jarak jauh membutuhkan energi yang lebih banyak lagi (menggunakan transmission amplifier)

![image](https://user-images.githubusercontent.com/10202888/95935855-6c9cc600-0dfe-11eb-8455-8617d3c9464a.png)

## LEACH Network Phase

![image](https://user-images.githubusercontent.com/10202888/95935939-93f39300-0dfe-11eb-9e86-ab348f21ed6b.png)

- Fase Set-Up
  - pembentukan cluster (bisa secara random)
  - tiap node punya kesempatan yang sama untuk menjadi cluster head (selama sebelumnya belum menjadi cluster head)
  - tiap node melakukan kalkulasi random apaka dirinya cluster head atau bukan
  - jika dia adalah cluster head, maka dia akan mengadvertise dirinya ke node lain
  - node yang bukan cluster head akan menerima advertise dari cluster head lain (bisa lebih dari satu), memilih cluster head terdekat, dan merespon balik ke cluster head yang dipilih tersebut
- Steady State
  - node yang bukan cluster head akan mengirimkan data ke cluster head dan kemudian cluster head akan mengagregasi data tersebut dan mengirimkannya ke sink
- RSSI = Received Signal Strength Indication

![image](https://user-images.githubusercontent.com/10202888/95936237-4fb4c280-0dff-11eb-9a89-8e6dd8a46d55.png)

- Algoritma penentuan cluster head
- dibuat sedemikian sehingga node akan menjadi cluster head setidaknya sekali

## LEACH-C

![image](https://user-images.githubusercontent.com/10202888/95936417-b89c3a80-0dff-11eb-9e60-597fc01b8e75.png)

- dikenal sebagai LEACH Centrallized

## Contoh Skenario

![image](https://user-images.githubusercontent.com/10202888/95936516-f4cf9b00-0dff-11eb-82c6-68b19920636a.png)

## Perbandingan Disipasi Energi

![image](https://user-images.githubusercontent.com/10202888/95936624-3eb88100-0e00-11eb-8c52-424002ca2a33.png)

## Bibliography

![image](https://user-images.githubusercontent.com/10202888/95936757-8939fd80-0e00-11eb-8618-8da128b754da.png)

</p></details>

**Comment by threeal** [comment]
# 4 - Zigbee Protocol

- Leech bagus, tapi tidak banyak diimplementasikan karena butuh sinkronisasi waktu antara cluster head dengan node lain.
- Slide materi ZigBee, [google drive](https://drive.google.com/file/d/1CUKkhBYi4S9XRDlhBtdQrqjiymB5-_MA/view?usp=sharing).
- Slide materi XBee, [google drive](https://drive.google.com/file/d/1Gh7pkhUhfvkBwBj2kLSoCtqEdTXvJWbY/view?usp=sharing).

<details><summary>detail bahasan</summary><p>

## Deskripsi

![image](https://user-images.githubusercontent.com/10202888/96664723-a0876680-137d-11eb-969c-e18979f574bb.png)

- bagian zigbee Alliance merupakanlibrary yang bisa digunakan untuk protocol Zigbee
- Zigbee mempunyai keunggulan low-cost, low-power, dan cocok untuk power supply baterai
- Zigbee dibangun diatas physical layer dan mac layer
- distandarisasi oleh Zigbee Alliance
- Zigbee digunakan pada WPAN (wireless personal area network)

## Wireless Space

![image](https://user-images.githubusercontent.com/10202888/96665150-6ff3fc80-137e-11eb-843c-7edd01e1f596.png)

- disini Zigbee memiliki data rate paling rendah, bahkan lebih rendah dari bluetooth, namun dengan data rate yang cepat, bluetooth terhitung memiliki power consumption yang besar sehingga kurang cocok digunakan untuk WSN.
- LORA terhitung kalah cepat dari wi-fi, tapi keungggulan dari LORA adalah jangkauannya yang lebih luas
- Contoh penggunaan LORA adalah sebagai alat komunikasi untuk perahu kecil (karena kapal besar sudah memiliki sistem sendiri yang bernama AIS / Automatic Identification System)

## Keunggulan Zigbee

![image](https://user-images.githubusercontent.com/10202888/96665746-ce6daa80-137f-11eb-98b3-47b3e40069f6.png)

- Zigbee lebih efektif karena memiliki mode sleep dimana perangkat komunikasi sedang off
- Mode aktif zigbee ada tiga, tx (mengirim), rx (menerima), dan idle (aktif namun tidak sedang mengirim maupun menerima)
- sleep masih membutuhkan energi karena tidak semua komponen mati, hanya untuk komunikasi data

## Topologi Zigbee

![image](https://user-images.githubusercontent.com/10202888/96666011-71262900-1380-11eb-90af-b2277808d82d.png)

- dalam satu PAN harus ada satu koordinator, beberapa router, dan beberapa end node

## Implementasi Zigbee

![image](https://user-images.githubusercontent.com/10202888/96666264-f7db0600-1380-11eb-8546-4358eeb9a414.png)

## XBee

![image](https://user-images.githubusercontent.com/10202888/96666752-fb22c180-1381-11eb-939b-5eee5ad24397.png)

- salah satu produk yang menggunakan protokol Zigbee

![image](https://user-images.githubusercontent.com/10202888/96667041-7b492700-1382-11eb-9138-32e503a71b13.png)

## Tipe XBee

![image](https://user-images.githubusercontent.com/10202888/96667157-b3506a00-1382-11eb-9bd2-38d35eb0cfde.png)

- harus memiliki kanal yang sama agar bisa berkomunikasi

## Konfigurasi XBee

![image](https://user-images.githubusercontent.com/10202888/96667230-dda22780-1382-11eb-98b1-70fbc888b890.png)

- konfigurasi bisa dilakukan menggunakan XCTU

## Konfigurasi End Device dan Coordinator

![image](https://user-images.githubusercontent.com/10202888/96667493-599c6f80-1383-11eb-8e86-36241a001b0a.png)

</p></details>

**Comment by threeal** [comment]
# 7 - Internet of Things

- Modul IoT CommTech, [google drive](https://drive.google.com/file/d/1hAWWa4k3_ulQQcrN-v21au3p5_mqK_fz/view?usp=sharing).

**Comment by threeal** [comment]
# 9 - MQTT

<details><summary>detail bahasan</summary><p>

## Messaging Protocols for Internet of Things

![image](https://user-images.githubusercontent.com/10202888/100170419-36239200-2ef8-11eb-8cd2-e71d970e5024.png)

- publisher mengirim data, subscriber menerima data.

## IoT Ecosystem

![image](https://user-images.githubusercontent.com/10202888/100170488-62d7a980-2ef8-11eb-82ed-4f8d9e1b21c0.png)

- session adalah suatu protokol, defaultnya MQTT, bisa menggunakan protokol lain seperti HTTP

## MQ Telemetry Transport (MQTT)

![image](https://user-images.githubusercontent.com/10202888/100171357-59027600-2ef9-11eb-8218-2709b5a6980c.png)

- ada broker yang menampung semua data dari publisher
- lightweight berarti untuk low network bandwith, sehingga cocok untuk LoRa karena tidak bisa cepat, namun hemat energy.

![image](https://user-images.githubusercontent.com/10202888/100171824-9a932100-2ef9-11eb-9098-6eda462b199d.png)

## MQTT Concepts

![image](https://user-images.githubusercontent.com/10202888/100171908-c6160b80-2ef9-11eb-91d5-f8fcd409e67c.png)

- pesan dipublish ke suatu topik, client bisa subscribe ke suatu topik maupun beberapa topik yang sama.

![image](https://user-images.githubusercontent.com/10202888/100171975-e940bb00-2ef9-11eb-88f3-c93a21c929a1.png)

- terdapat QoS (Quality of Service), setidaknya terdapat 3 macam mode.

## MQTT Example

![image](https://user-images.githubusercontent.com/10202888/100172245-76840f80-2efa-11eb-9476-d47a12a6f8f8.png)

- MQTT Broker menampung berbagai data dari sensor sensor.
- antar broker dengan broker bisa berkomunikasi juga jika terhubung oleh bridge.
- subscriber bisa meminta data dari publisher di broker lain yang terhubung melalui bridge

## MQTT Application Examples

![image](https://user-images.githubusercontent.com/10202888/100172411-d67ab600-2efa-11eb-8130-1fc884cb20c5.png)

- di sini home monitoring appliance bisa berguna sebagai subscriber juga semisal untuk meminta data dari analytical application.

## MQTT vs. HTTP

![image](https://user-images.githubusercontent.com/10202888/100172708-7df7e880-2efb-11eb-9c43-768143a002db.png)

## Single Board Microcontrollers

![image](https://user-images.githubusercontent.com/10202888/100172924-fa8ac700-2efb-11eb-9476-4f14dfadf6b1.png)

</p></details>

**Comment by threeal** [comment]
EAS Sudah berakhir, have a nice day

**Comment by threeal** [comment]
masih ada tanggungan FP

**Comment by threeal** [comment]
FP udah selesai, have a nice day
