### ISSUE TITLE
Bahasan Gatel

### ISSUE THREAD

**Issue by threeal** [threeal-archive/research#14]
### Task

- [x] ngumpulin proposal [ini](https://docs.google.com/document/d/1LLHFuL4_msvfO0kqCVmcLcqdtYOLzzNYvQBzAqhaDdo/edit) di [sini](https://intip.in/Nejp) (DEADLINE 6 OKTOBER)
- [x] ngumpulin revisi proposal [ini](https://docs.google.com/document/d/1LLHFuL4_msvfO0kqCVmcLcqdtYOLzzNYvQBzAqhaDdo/edit) di [sini](https://intip.in/6Ljs) (DEADLINE 13 OKTOBER)
- [x] tampilan awal web
- [x] sistem awal database
- [x] mockup AR (ngikut [ini](https://codelabs.developers.google.com/codelabs/location-places-arcore-android/index.html) atau nyoba [ini](https://github.com/appoly/ARCore-Location))
- [x] Ngumpulin laporan akhir [ini](https://drive.google.com/drive/folders/176PIqK9zv1eTDMtMFdM_UzaZ4Y74UCwT?usp=sharing) di [sini](https://intip.in/Wxcf)

**Comment by threeal** [comment]
- full ppt di [sini](https://drive.google.com/file/d/1DnBjhM9nxCOQBETyysvStO4W2OJPEkVP/view?usp=sharing)
- contoh laporan kelompok [kalori](https://drive.google.com/file/d/12Pn1U8spraBuhJwnX4fAlKzEKAqmHRcs/view?usp=sharing), [lampu](https://drive.google.com/file/d/15KHp55UpRVSGVzJqYSvkV_7dX1frU9kC/view?usp=sharing), [tangan](https://drive.google.com/file/d/1or-ztememlFOjfI5PT1P_VxBnCbxKBCl/view?usp=sharing)
- contoh laporan individu [sarah](https://drive.google.com/file/d/14xshZ-1KhhTXc5CpFMlZS1cWga9HQSnD/view?usp=sharing), [raffly](https://drive.google.com/file/d/1y5U7JpeS-NuJqxefuaXCFbNF46KVrGhi/view?usp=sharing), 
- kumpulan fp protel di [sini](https://intip.in/FinalProjectProtel2020)

<details><summary>detail bahasan</summary><p>

### Objective

- Membuat suatu produk
- Membuat perencanaan
- Desain
- Implementasi
- Report (HAKI, PKM, Publikasi)

### Alur

- Kenali permasalahan
- Temukan fitur permasalahan
- Tentukan parameter yang akan diukur
- Tentukan perangkat / sensor yang akan digunakan untuk mendapatkan nilai parameter
- Tentukan metode pengukuran dan perhitungan hasil pengukuran
- Tentukan algoritma keputusan dalam merespon hasil pengukuran
- Lakukan validasi hasil pengukuran dan algoritma
- Ukur akurasi dan prosentase keberhasilan sistem
- Tentukan bentuk packaging yang pas dan menjual
- Tentukan fitur alat secara keseluruhan
- Lakukan dokumentasi teknis yang detail dan lengkap
- Lakukan dokumentasi user manual cara penggunaan
- Tentukan teknik pemasaran yang akan anda lakukan

### Proposal Project

- Nama Project
- Permasalahan
- Solusi yang ditawarkan
- Cara Kerja alat
- Algoritma, Flow chart, Use case Diagram, Blok Diagram, dll
- Nama anggota Tim dan jobdisc
- Time Schdule

### Group Weekly Report (Hardcopy)

- Nama Project
- Nama Tim Leader
- Progress this week
  - Engineering Report
  - Problem
  - Solution
- Plan for next week (Engineering Report)

### Individual Weekly Report (Softcopy)

- Nama Project
- Progress this week
  - Engineering Report
  - Problem
  - Solution
- Plan for next week (Engineering Report)

### Final Report

- Report Kelompok (hardcopy) -> Product Profile, user manual
- Report Individu (hardcopy) Engineering Report, (Product, sistem) Testing Report
  - Algoritma, Flow chart, Use case Diagram, Blok Diagram
  - DFD, ER, Structure DB, Server configuration
  - Desain sistem, schematic, network architecture, data protocol
  - Proses Bisnis
  - dll
- Video Profile
- Draft HAKI
- Dalam satu CD
  - Report Kelompok
  - Report Individu
  - Video Profile product
  - Source code
  - Source desain UI

### Report

- Nama
- Fungsi dan fitur
- Desain
- Cara kerja
- Pengujian
- Acknowledgement pada pembuat resource yang anda gunakan. (juga
ditampilkan pada video profile)

### Video profile project telematika

- Profile MK
- Profile project (kumpulan video profile project)
- Wawancara dengan peserta MK
- Wawancara dengan audience

</p></details>

**Comment by threeal** [comment]
nilai sudah keluar, have a nice day
